### PR TITLE
Add case sensitivity

### PR DESCRIPTION
**Pull request by chadrik**
In order to meet the needs of the growing number of flow-based applications, the .fbp spec should support case sensitive port names.  

Prior to this PR, the behavior of this tool was to convert port names to lower-case, and also, in the case of EXPORT/INPORT/OUTPORT statements to convert node names to lower-case.  This caused problems for a number of users and use-cases:  https://github.com/noflo/noflo-ui/issues/496, https://github.com/flowbased/fbp/issues/30

This PR modifies the parser to allow lower- and mixed-case port names and to preserve the parsed names in the resulting json output.

For example, this graph is supported with the new changes:

```
'Hello' -> in Foo(Component)
'World' -> inPut Bar(OtherComponent)
Foo outPut -> data Bar
```

Other notes:

1.  Ports and components must now begin with a letter or underscore.   This convention spans most programming languages, so it should be familiar to users.  I added the change to this commit because it avoids difficult-to-parse (and difficult-to-read) scenarios like `'foo' -> 0[1] 2(MyComponent)`, where `0` and `2` are port and node names and `1` is an array index.  These were previously acceptable according to the grammar (I assume this was an oversight rather than a design choice). 

2. Values set with `EXPORT=` / `INPORT=` / `OUTPORT=` are no longer required to be all CAPS and the original case is preserved by the parser.  This means that .fbp graphs which refer to nodes in these statements using all CAPS despite the fact that the actual node names are lower- or mixed-case should be adjusted to use actual names.  

   Previously, names did not match and relied on the application reading the data to perform a case-insensitive match (i.e. `READ` != `Read`):

    ```
    INPORT=READ.IN:FILENAME
    Read(ReadFile) OUT -> IN Display(Output) 
    ```

   Now names can and should match:

    ```
    INPORT=Read.IN:FILENAME
    Read(ReadFile) OUT -> IN Display(Output) 
    ```

This PR breaks backward compatibility and warrants a major version change. Tools which use the .fbp format to store graphs are expected to write .fbp files with the exact port names expected by their application.

### CODE REVIEW

**Comment by bergie** [comment]
Relevant discussion: https://groups.google.com/d/msg/flow-based-programming/bu9K180Pq_o/pQphUZikCAAJ

**Comment by jonnor** [comment]
Getting rid of the enforced peculiarities around case is good. However I think this PR should add an option to . And then clearly mark the old behavior as deprecated, to be dropped in next major release.
This allows us to merge and release it right away, as it won't break compatibility. And it avoids everyone using the dependency to do have a flag-day (everything at once) migration.

**Comment by chadrik** [comment]
@jonnor, Agreed.  Will have something soon.

**Comment by chadrik** [comment]
Added a `caseSensitive` option, which is off by default.    The build is failing for a reason unrelated to the code change:

```
npm ERR! peerinvalid The package phantomjs@1.9.7-15 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mocha-phantomjs@3.5.6 wants phantomjs@~1.9.1
```

Any idea what that's all about?

**Comment by jonnor** [comment]
Looking much better. But why were all(?) the existing tests changed to use the case-sensitive flag? Do we have any tests that test that the existing functionality did not break?

**Comment by jonnor** [comment]
@chadrik if you merge in master, the build errors should be fixed. We were way behind on bunch of dependencies, and something changed upstream in some of them that was incompatible.

**Comment by ifitzpatrick** [comment]
The idea with the tests was to treat the old case insensitive behavior as deprecated. There is a new describe block at the bottom of the tests to make sure the existing behavior works: https://github.com/flowbased/fbp/pull/51/files#diff-3d3704951905eb1d0af9b01730231b34R509

**Comment by jonnor** [comment]
Ok. Nothing tests-the-tests, so in general I prefer minimal changes in tests.

**Comment by ifitzpatrick** [comment]
That's a good point. We will try not to make such extensive changes to tests in the future.

**Comment by jonnor** [comment]
Released in `fbp 1.2.0`

**Comment by jonnor** [comment]
Thanks!

**Pull request merged**
